UPDATE enrollments
SET status = 'STOPPED'
WHERE status IN ('DROPPED', 'COMPLETED');

CREATE TABLE enrollment_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    enrollment_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    reason VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_enrollment_status_history_enrollment
        FOREIGN KEY (enrollment_id) REFERENCES enrollments (id),
    CONSTRAINT chk_enrollment_status_history_dates
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT chk_enrollment_status_history_status
        CHECK (status IN ('ACTIVE', 'ON_HOLD', 'STOPPED', 'TRANSFERRED', 'CANCELED'))
);

INSERT INTO enrollment_status_history (
    enrollment_id,
    status,
    effective_from,
    effective_to,
    reason,
    created_at
)
SELECT id,
       'ACTIVE',
       start_date,
       CASE
           WHEN status = 'STOPPED' AND end_date IS NOT NULL THEN end_date
           WHEN status = 'TRANSFERRED' AND end_date IS NOT NULL THEN end_date + 1
           ELSE NULL
       END,
       'Backfilled active enrollment period',
       created_at
FROM enrollments
WHERE status = 'ACTIVE'
   OR (
      status IN ('STOPPED', 'TRANSFERRED')
      AND end_date IS NOT NULL
      AND CASE
          WHEN status = 'TRANSFERRED' THEN end_date + 1
          ELSE end_date
      END >= start_date
   );

INSERT INTO enrollment_status_history (
    enrollment_id,
    status,
    effective_from,
    effective_to,
    reason,
    created_at
)
SELECT id,
       status,
       CASE
           WHEN status = 'TRANSFERRED' AND end_date IS NOT NULL
               THEN GREATEST(start_date, end_date + 1)
           WHEN status = 'STOPPED' AND end_date IS NOT NULL
               THEN GREATEST(start_date, end_date)
           ELSE start_date
       END,
       NULL,
       'Backfilled from enrollment current status',
       updated_at
FROM enrollments
WHERE status <> 'ACTIVE';

CREATE UNIQUE INDEX uq_enrollment_status_history_open
    ON enrollment_status_history (enrollment_id)
    WHERE effective_to IS NULL;

CREATE INDEX idx_enrollment_status_history_eligibility
    ON enrollment_status_history (enrollment_id, status, effective_from, effective_to);

CREATE INDEX idx_enrollment_status_history_active_period
    ON enrollment_status_history (status, effective_from, effective_to, enrollment_id);
