-- Finance V1: accounts, categories, cash ledger, financial periods
-- Missing FinancialPeriod rows are treated as OPEN by application logic.

CREATE TABLE financial_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(20) NOT NULL,
    opening_balance NUMERIC(19, 2) NOT NULL,
    opening_balance_date DATE NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    note VARCHAR(1000) NULL,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(100) NULL,
    updated_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(100) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_financial_accounts_code UNIQUE (code),
    CONSTRAINT chk_financial_accounts_type CHECK (type IN ('CASH', 'BANK', 'OTHER'))
);

CREATE INDEX idx_financial_accounts_active ON financial_accounts (active);
CREATE INDEX idx_financial_accounts_type ON financial_accounts (type);

CREATE TABLE transaction_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    direction VARCHAR(20) NOT NULL,
    parent_id BIGINT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    system_category BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_transaction_categories_code UNIQUE (code),
    CONSTRAINT chk_transaction_categories_direction CHECK (direction IN ('INCOME', 'EXPENSE')),
    CONSTRAINT fk_transaction_categories_parent FOREIGN KEY (parent_id) REFERENCES transaction_categories (id)
);

CREATE INDEX idx_transaction_categories_direction ON transaction_categories (direction);
CREATE INDEX idx_transaction_categories_active ON transaction_categories (active);

CREATE TABLE financial_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    year INT NOT NULL,
    month INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    closed_at TIMESTAMP NULL,
    closed_by VARCHAR(100) NULL,
    reopened_at TIMESTAMP NULL,
    reopened_by VARCHAR(100) NULL,
    reopen_reason VARCHAR(1000) NULL,
    note VARCHAR(1000) NULL,
    opening_balance_snapshot NUMERIC(19, 2) NULL,
    total_income_snapshot NUMERIC(19, 2) NULL,
    total_expense_snapshot NUMERIC(19, 2) NULL,
    closing_balance_snapshot NUMERIC(19, 2) NULL,
    outstanding_debt_snapshot NUMERIC(19, 2) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_financial_periods_year_month UNIQUE (year, month),
    CONSTRAINT chk_financial_periods_month CHECK (month >= 1 AND month <= 12),
    CONSTRAINT chk_financial_periods_status CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE INDEX idx_financial_periods_status ON financial_periods (status);

CREATE TABLE cash_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    transaction_code VARCHAR(50) NOT NULL,
    transaction_date DATE NOT NULL,
    account_id BIGINT NOT NULL,
    direction VARCHAR(10) NOT NULL,
    category_id BIGINT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    source_id BIGINT NULL,
    reference_no VARCHAR(100) NULL,
    payer_or_payee VARCHAR(200) NULL,
    description VARCHAR(1000) NOT NULL,
    attachment_reference VARCHAR(500) NULL,
    transfer_group_id VARCHAR(50) NULL,
    original_transaction_id BIGINT NULL,
    reversal_transaction_id BIGINT NULL,
    reversal_reason VARCHAR(1000) NULL,
    posted_at TIMESTAMP NULL,
    reversed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(100) NULL,
    updated_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(100) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_cash_transactions_code UNIQUE (transaction_code),
    CONSTRAINT chk_cash_transactions_direction CHECK (direction IN ('IN', 'OUT')),
    CONSTRAINT chk_cash_transactions_status CHECK (status IN ('DRAFT', 'POSTED', 'REVERSED')),
    CONSTRAINT chk_cash_transactions_amount CHECK (amount > 0),
    CONSTRAINT chk_cash_transactions_source_type CHECK (source_type IN (
        'PAYMENT', 'MANUAL_INCOME', 'MANUAL_EXPENSE', 'TRANSFER',
        'OPENING_BALANCE', 'ADJUSTMENT', 'REVERSAL', 'REFUND'
    )),
    CONSTRAINT fk_cash_transactions_account FOREIGN KEY (account_id) REFERENCES financial_accounts (id),
    CONSTRAINT fk_cash_transactions_category FOREIGN KEY (category_id) REFERENCES transaction_categories (id),
    CONSTRAINT fk_cash_transactions_original FOREIGN KEY (original_transaction_id) REFERENCES cash_transactions (id),
    CONSTRAINT fk_cash_transactions_reversal FOREIGN KEY (reversal_transaction_id) REFERENCES cash_transactions (id)
);

CREATE INDEX idx_cash_transactions_date ON cash_transactions (transaction_date);
CREATE INDEX idx_cash_transactions_account_id ON cash_transactions (account_id);
CREATE INDEX idx_cash_transactions_category_id ON cash_transactions (category_id);
CREATE INDEX idx_cash_transactions_source ON cash_transactions (source_type, source_id);
CREATE INDEX idx_cash_transactions_transfer_group ON cash_transactions (transfer_group_id);
CREATE INDEX idx_cash_transactions_status ON cash_transactions (status);
CREATE INDEX idx_cash_transactions_direction ON cash_transactions (direction);

-- Idempotency: at most one non-reversal PAYMENT ledger row per payment id
CREATE UNIQUE INDEX uk_cash_transactions_payment_source
    ON cash_transactions (source_type, source_id)
    WHERE source_type = 'PAYMENT' AND source_id IS NOT NULL AND status <> 'DRAFT'
      AND original_transaction_id IS NULL;

-- Seed default accounts
INSERT INTO financial_accounts (
    code, name, type, opening_balance, opening_balance_date, active, note, display_order,
    created_at, updated_at, version
) VALUES
    ('CASH_CENTER', 'Tiền mặt tại trung tâm', 'CASH', 0, CURRENT_DATE, TRUE, 'Tài khoản tiền mặt mặc định', 1, NOW(), NOW(), 0),
    ('VCB', 'Vietcombank', 'BANK', 0, CURRENT_DATE, TRUE, 'Tài khoản ngân hàng mặc định', 2, NOW(), NOW(), 0),
    ('MB', 'MB Bank', 'BANK', 0, CURRENT_DATE, TRUE, NULL, 3, NOW(), NOW(), 0);

-- Seed income categories
INSERT INTO transaction_categories (
    code, name, direction, parent_id, active, system_category, display_order, created_at, updated_at
) VALUES
    ('TUITION', 'Học phí', 'INCOME', NULL, TRUE, TRUE, 1, NOW(), NOW()),
    ('BOOK_INCOME', 'Tiền sách', 'INCOME', NULL, TRUE, TRUE, 2, NOW(), NOW()),
    ('MATERIAL_INCOME', 'Tiền tài liệu', 'INCOME', NULL, TRUE, TRUE, 3, NOW(), NOW()),
    ('OTHER_INCOME', 'Thu khác', 'INCOME', NULL, TRUE, TRUE, 4, NOW(), NOW());

-- Explicit Payment → FinancialAccount mapping for tuition ledger posting
ALTER TABLE payments
    ADD COLUMN financial_account_id BIGINT NULL;

ALTER TABLE payments
    ADD CONSTRAINT fk_payments_financial_account
        FOREIGN KEY (financial_account_id) REFERENCES financial_accounts (id);

CREATE INDEX idx_payments_financial_account_id ON payments (financial_account_id);

-- Seed expense categories
INSERT INTO transaction_categories (
    code, name, direction, parent_id, active, system_category, display_order, created_at, updated_at
) VALUES
    ('CHALK', 'Phấn', 'EXPENSE', NULL, TRUE, TRUE, 10, NOW(), NOW()),
    ('PAPER', 'Giấy', 'EXPENSE', NULL, TRUE, TRUE, 11, NOW(), NOW()),
    ('PRINTER_INK', 'Mực in', 'EXPENSE', NULL, TRUE, TRUE, 12, NOW(), NOW()),
    ('BOOK_EXPENSE', 'Sách và giáo trình', 'EXPENSE', NULL, TRUE, TRUE, 13, NOW(), NOW()),
    ('TEACHING_MATERIAL', 'Tài liệu học tập', 'EXPENSE', NULL, TRUE, TRUE, 14, NOW(), NOW()),
    ('STATIONERY', 'Văn phòng phẩm', 'EXPENSE', NULL, TRUE, TRUE, 15, NOW(), NOW()),
    ('TEACHER_SALARY', 'Lương giáo viên', 'EXPENSE', NULL, TRUE, TRUE, 16, NOW(), NOW()),
    ('RENT', 'Thuê mặt bằng', 'EXPENSE', NULL, TRUE, TRUE, 17, NOW(), NOW()),
    ('ELECTRICITY', 'Tiền điện', 'EXPENSE', NULL, TRUE, TRUE, 18, NOW(), NOW()),
    ('WATER', 'Tiền nước', 'EXPENSE', NULL, TRUE, TRUE, 19, NOW(), NOW()),
    ('INTERNET', 'Internet', 'EXPENSE', NULL, TRUE, TRUE, 20, NOW(), NOW()),
    ('MARKETING', 'Marketing', 'EXPENSE', NULL, TRUE, TRUE, 21, NOW(), NOW()),
    ('EQUIPMENT', 'Thiết bị', 'EXPENSE', NULL, TRUE, TRUE, 22, NOW(), NOW()),
    ('REPAIR', 'Sửa chữa', 'EXPENSE', NULL, TRUE, TRUE, 23, NOW(), NOW()),
    ('OTHER_EXPENSE', 'Chi khác', 'EXPENSE', NULL, TRUE, TRUE, 24, NOW(), NOW());
