-- Minimal system settings store. finance.start_date is the first valid finance tracking date.

CREATE TABLE system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    setting_key VARCHAR(100) NOT NULL,
    setting_value VARCHAR(500) NOT NULL,
    description VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_system_settings_key UNIQUE (setting_key)
);

INSERT INTO system_settings (setting_key, setting_value, description, created_at, updated_at)
VALUES (
    'finance.start_date',
    '2026-05-01',
    'First date from which the center financial data is valid',
    NOW(),
    NOW()
);
