ALTER TABLE student_packages
    ADD COLUMN calculated_period_start_date DATE NULL,
    ADD COLUMN calculated_period_end_date DATE NULL,
    ADD COLUMN manual_period_start_date DATE NULL,
    ADD COLUMN period_needs_recalculation BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE student_packages
SET calculated_period_start_date = start_date;

CREATE TABLE student_package_period_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    student_package_id BIGINT NOT NULL,
    old_effective_start_date DATE NULL,
    new_manual_start_date DATE NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    changed_at TIMESTAMP NOT NULL,
    changed_by VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_package_period_adjustments_package
        FOREIGN KEY (student_package_id) REFERENCES student_packages (id)
);

CREATE INDEX idx_package_period_adjustments_package
    ON student_package_period_adjustments (student_package_id, changed_at DESC);
