CREATE TABLE teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    teacher_code VARCHAR(50) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NULL,
    phone VARCHAR(30) NULL,
    status VARCHAR(20) NOT NULL,
    note VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_teachers_teacher_code UNIQUE (teacher_code)
);

CREATE INDEX idx_teachers_full_name ON teachers (full_name);
CREATE INDEX idx_teachers_status ON teachers (status);
CREATE INDEX idx_teachers_email ON teachers (email);

ALTER TABLE classrooms
    ADD COLUMN teacher_id BIGINT NULL;

ALTER TABLE classrooms
    ADD CONSTRAINT fk_classrooms_teacher
        FOREIGN KEY (teacher_id) REFERENCES teachers (id);

CREATE INDEX idx_classrooms_teacher_id ON classrooms (teacher_id);
