CREATE TABLE user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(100) NOT NULL,
    normalized_username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    student_id BIGINT NULL,
    teacher_id BIGINT NULL,
    must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP NULL,
    last_login_at TIMESTAMP NULL,
    password_changed_at TIMESTAMP NULL,
    token_version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(100) NULL,
    updated_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(100) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_user_accounts_normalized_username UNIQUE (normalized_username),
    CONSTRAINT uk_user_accounts_student_id UNIQUE (student_id),
    CONSTRAINT uk_user_accounts_teacher_id UNIQUE (teacher_id),
    CONSTRAINT fk_user_accounts_student
        FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_user_accounts_teacher
        FOREIGN KEY (teacher_id) REFERENCES teachers (id),
    CONSTRAINT ck_user_accounts_role_profile CHECK (
        (role = 'ADMIN' AND student_id IS NULL AND teacher_id IS NULL)
        OR (role = 'STUDENT' AND student_id IS NOT NULL AND teacher_id IS NULL)
        OR (role = 'TEACHER' AND teacher_id IS NOT NULL AND student_id IS NULL)
    )
);

CREATE INDEX idx_user_accounts_username ON user_accounts (username);
CREATE INDEX idx_user_accounts_role ON user_accounts (role);
CREATE INDEX idx_user_accounts_status ON user_accounts (status);
CREATE INDEX idx_user_accounts_student_id ON user_accounts (student_id);
CREATE INDEX idx_user_accounts_teacher_id ON user_accounts (teacher_id);
