-- Billing-cycle clarity on invoices + center profile for printable documents.

ALTER TABLE invoices
    ADD COLUMN cycle_no INT NULL,
    ADD COLUMN effective_from DATE NULL,
    ADD COLUMN package_price_snapshot NUMERIC(19, 2) NULL,
    ADD COLUMN package_id BIGINT NULL;

ALTER TABLE invoices
    ADD CONSTRAINT fk_invoices_package
        FOREIGN KEY (package_id) REFERENCES tuition_packages (id);

CREATE INDEX idx_invoices_cycle_no ON invoices (cycle_no);
CREATE INDEX idx_invoices_effective_from ON invoices (effective_from);
CREATE INDEX idx_invoices_due_date ON invoices (due_date);
CREATE INDEX idx_invoices_package_id ON invoices (package_id);

-- Stable cycle numbering: one StudentPackage cycle per enrollment.
ALTER TABLE student_packages
    ADD CONSTRAINT uk_student_packages_enrollment_cycle UNIQUE (enrollment_id, cycle_no);

-- Prefer 1:1 Invoice ↔ StudentPackage when unambiguous (already FK).
-- Backfill billing fields from linked StudentPackage (safe, historical snapshot source).
UPDATE invoices invoice
SET
    cycle_no = sp.cycle_no,
    effective_from = sp.start_date,
    package_price_snapshot = COALESCE(invoice.package_price_snapshot, sp.price, invoice.amount),
    package_id = sp.tuition_package_id
FROM student_packages sp
WHERE invoice.student_package_id = sp.id
  AND (
      invoice.cycle_no IS NULL
      OR invoice.effective_from IS NULL
      OR invoice.package_price_snapshot IS NULL
      OR invoice.package_id IS NULL
  );

-- Seed invoice due-days setting (default 7). Do not rewrite existing due_date values.
INSERT INTO system_settings (setting_key, setting_value, description, created_at, updated_at)
VALUES (
    'invoice.due_days',
    '7',
    'Number of days after issue date for invoice due date',
    NOW(),
    NOW()
)
ON CONFLICT (setting_key) DO NOTHING;

-- Center profile for printable tuition notices and payment receipts.
CREATE TABLE center_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    center_name VARCHAR(255) NOT NULL,
    center_subtitle VARCHAR(255) NULL,
    logo_url VARCHAR(1000) NULL,
    address VARCHAR(500) NULL,
    phone VARCHAR(50) NULL,
    email VARCHAR(255) NULL,
    website VARCHAR(255) NULL,
    tax_code VARCHAR(50) NULL,
    bank_name VARCHAR(255) NULL,
    bank_account_number VARCHAR(100) NULL,
    bank_account_name VARCHAR(255) NULL,
    payment_instruction VARCHAR(1000) NULL,
    invoice_footer_note VARCHAR(1000) NULL,
    receipt_footer_note VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO center_profiles (
    center_name,
    center_subtitle,
    payment_instruction,
    invoice_footer_note,
    receipt_footer_note,
    created_at,
    updated_at
) VALUES (
    'Trung tâm Anh ngữ',
    NULL,
    'Vui lòng thanh toán đúng hạn. Nội dung chuyển khoản gợi ý: [Mã học viên] [Mã hóa đơn]',
    'Trân trọng cảm ơn Quý phụ huynh đã đồng hành cùng trung tâm.',
    'Phiếu thu này là chứng từ ghi nhận khoản thanh toán học phí.',
    NOW(),
    NOW()
);
