-- Phase 11: Learning content, assignments, assessments, evaluations, progress reports

CREATE TABLE evaluation_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200) NOT NULL,
    classroom_id BIGINT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    reopen_reason VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_evaluation_periods_classroom FOREIGN KEY (classroom_id) REFERENCES classrooms (id),
    CONSTRAINT chk_evaluation_periods_dates CHECK (start_date <= end_date)
);

CREATE INDEX idx_evaluation_periods_classroom_id ON evaluation_periods (classroom_id);
CREATE INDEX idx_evaluation_periods_status ON evaluation_periods (status);
CREATE INDEX idx_evaluation_periods_dates ON evaluation_periods (start_date, end_date);

CREATE TABLE lesson_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    class_session_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    objectives TEXT NULL,
    planned_content TEXT NULL,
    actual_content TEXT NULL,
    vocabulary TEXT NULL,
    grammar_topics TEXT NULL,
    skills TEXT NULL,
    homework_instruction TEXT NULL,
    teacher_note TEXT NULL,
    status VARCHAR(20) NOT NULL,
    created_by VARCHAR(100) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(100) NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_lesson_records_session FOREIGN KEY (class_session_id) REFERENCES class_sessions (id),
    CONSTRAINT uk_lesson_records_session UNIQUE (class_session_id)
);

CREATE INDEX idx_lesson_records_status ON lesson_records (status);

CREATE TABLE assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    instructions TEXT NULL,
    classroom_id BIGINT NOT NULL,
    lesson_record_id BIGINT NULL,
    assigned_date DATE NOT NULL,
    due_date DATE NULL,
    max_score NUMERIC(19, 2) NULL,
    allow_submission BOOLEAN NOT NULL DEFAULT TRUE,
    allow_late_submission BOOLEAN NOT NULL DEFAULT FALSE,
    target_mode VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_by_teacher_id BIGINT NULL,
    created_by VARCHAR(100) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_assignments_classroom FOREIGN KEY (classroom_id) REFERENCES classrooms (id),
    CONSTRAINT fk_assignments_lesson FOREIGN KEY (lesson_record_id) REFERENCES lesson_records (id),
    CONSTRAINT fk_assignments_teacher FOREIGN KEY (created_by_teacher_id) REFERENCES teachers (id),
    CONSTRAINT chk_assignments_due_date CHECK (due_date IS NULL OR due_date >= assigned_date),
    CONSTRAINT chk_assignments_max_score CHECK (max_score IS NULL OR max_score > 0)
);

CREATE INDEX idx_assignments_classroom_id ON assignments (classroom_id);
CREATE INDEX idx_assignments_status ON assignments (status);
CREATE INDEX idx_assignments_due_date ON assignments (due_date);
CREATE INDEX idx_assignments_teacher_id ON assignments (created_by_teacher_id);

CREATE TABLE assignment_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    assignment_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_assignment_targets_assignment FOREIGN KEY (assignment_id) REFERENCES assignments (id),
    CONSTRAINT fk_assignment_targets_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT uk_assignment_targets UNIQUE (assignment_id, student_id)
);

CREATE INDEX idx_assignment_targets_student_id ON assignment_targets (student_id);

CREATE TABLE assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    classroom_id BIGINT NOT NULL,
    class_session_id BIGINT NULL,
    evaluation_period_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    type VARCHAR(30) NOT NULL,
    assessment_date DATE NOT NULL,
    max_score NUMERIC(19, 2) NOT NULL,
    weight NUMERIC(19, 2) NULL,
    status VARCHAR(20) NOT NULL,
    published_to_students BOOLEAN NOT NULL DEFAULT FALSE,
    created_by_teacher_id BIGINT NULL,
    created_by VARCHAR(100) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_assessments_classroom FOREIGN KEY (classroom_id) REFERENCES classrooms (id),
    CONSTRAINT fk_assessments_session FOREIGN KEY (class_session_id) REFERENCES class_sessions (id),
    CONSTRAINT fk_assessments_period FOREIGN KEY (evaluation_period_id) REFERENCES evaluation_periods (id),
    CONSTRAINT fk_assessments_teacher FOREIGN KEY (created_by_teacher_id) REFERENCES teachers (id),
    CONSTRAINT chk_assessments_max_score CHECK (max_score > 0),
    CONSTRAINT chk_assessments_weight CHECK (weight IS NULL OR weight > 0)
);

CREATE INDEX idx_assessments_classroom_id ON assessments (classroom_id);
CREATE INDEX idx_assessments_status ON assessments (status);
CREATE INDEX idx_assessments_date ON assessments (assessment_date);
CREATE INDEX idx_assessments_period_id ON assessments (evaluation_period_id);
CREATE INDEX idx_assessments_teacher_id ON assessments (created_by_teacher_id);

CREATE TABLE learning_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    file_name VARCHAR(255) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(150) NOT NULL,
    file_size BIGINT NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    classroom_id BIGINT NOT NULL,
    lesson_record_id BIGINT NULL,
    assignment_id BIGINT NULL,
    assessment_id BIGINT NULL,
    visibility VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    uploaded_by VARCHAR(100) NULL,
    uploaded_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_learning_materials_classroom FOREIGN KEY (classroom_id) REFERENCES classrooms (id),
    CONSTRAINT fk_learning_materials_lesson FOREIGN KEY (lesson_record_id) REFERENCES lesson_records (id),
    CONSTRAINT fk_learning_materials_assignment FOREIGN KEY (assignment_id) REFERENCES assignments (id),
    CONSTRAINT fk_learning_materials_assessment FOREIGN KEY (assessment_id) REFERENCES assessments (id)
);

CREATE INDEX idx_learning_materials_classroom_id ON learning_materials (classroom_id);
CREATE INDEX idx_learning_materials_lesson_id ON learning_materials (lesson_record_id);
CREATE INDEX idx_learning_materials_assignment_id ON learning_materials (assignment_id);
CREATE INDEX idx_learning_materials_assessment_id ON learning_materials (assessment_id);
CREATE INDEX idx_learning_materials_active ON learning_materials (active);

CREATE TABLE assignment_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    assignment_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    text_answer TEXT NULL,
    status VARCHAR(20) NOT NULL,
    teacher_score NUMERIC(19, 2) NULL,
    teacher_feedback TEXT NULL,
    graded_at TIMESTAMP NULL,
    graded_by VARCHAR(100) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_assignment_submissions_assignment FOREIGN KEY (assignment_id) REFERENCES assignments (id),
    CONSTRAINT fk_assignment_submissions_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT uk_assignment_submissions UNIQUE (assignment_id, student_id)
);

CREATE INDEX idx_assignment_submissions_student_id ON assignment_submissions (student_id);
CREATE INDEX idx_assignment_submissions_status ON assignment_submissions (status);

CREATE TABLE assignment_submission_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    submission_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(150) NOT NULL,
    file_size BIGINT NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_submission_attachments_submission FOREIGN KEY (submission_id) REFERENCES assignment_submissions (id)
);

CREATE INDEX idx_submission_attachments_submission_id ON assignment_submission_attachments (submission_id);

CREATE TABLE assessment_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    assessment_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    score NUMERIC(19, 2) NULL,
    status VARCHAR(20) NOT NULL,
    teacher_comment TEXT NULL,
    graded_by VARCHAR(100) NULL,
    graded_at TIMESTAMP NULL,
    published_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_assessment_scores_assessment FOREIGN KEY (assessment_id) REFERENCES assessments (id),
    CONSTRAINT fk_assessment_scores_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT uk_assessment_scores UNIQUE (assessment_id, student_id)
);

CREATE INDEX idx_assessment_scores_student_id ON assessment_scores (student_id);
CREATE INDEX idx_assessment_scores_status ON assessment_scores (status);

CREATE TABLE student_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    evaluation_period_id BIGINT NOT NULL,
    classroom_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    teacher_id BIGINT NULL,
    strengths TEXT NULL,
    areas_for_improvement TEXT NULL,
    learning_attitude TEXT NULL,
    participation TEXT NULL,
    homework_performance TEXT NULL,
    teacher_comment TEXT NULL,
    recommendation TEXT NULL,
    internal_note TEXT NULL,
    overall_rating VARCHAR(30) NULL,
    status VARCHAR(20) NOT NULL,
    published_at TIMESTAMP NULL,
    finalized_at TIMESTAMP NULL,
    reopen_reason VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_student_evaluations_period FOREIGN KEY (evaluation_period_id) REFERENCES evaluation_periods (id),
    CONSTRAINT fk_student_evaluations_classroom FOREIGN KEY (classroom_id) REFERENCES classrooms (id),
    CONSTRAINT fk_student_evaluations_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_student_evaluations_teacher FOREIGN KEY (teacher_id) REFERENCES teachers (id),
    CONSTRAINT uk_student_evaluations UNIQUE (evaluation_period_id, classroom_id, student_id)
);

CREATE INDEX idx_student_evaluations_classroom_id ON student_evaluations (classroom_id);
CREATE INDEX idx_student_evaluations_student_id ON student_evaluations (student_id);
CREATE INDEX idx_student_evaluations_teacher_id ON student_evaluations (teacher_id);
CREATE INDEX idx_student_evaluations_status ON student_evaluations (status);
CREATE INDEX idx_student_evaluations_period_id ON student_evaluations (evaluation_period_id);

CREATE TABLE student_progress_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    evaluation_id BIGINT NOT NULL,
    evaluation_period_id BIGINT NOT NULL,
    classroom_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    teacher_id BIGINT NULL,
    status VARCHAR(20) NOT NULL,
    published_at TIMESTAMP NULL,
    generated_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_progress_reports_evaluation FOREIGN KEY (evaluation_id) REFERENCES student_evaluations (id),
    CONSTRAINT fk_progress_reports_period FOREIGN KEY (evaluation_period_id) REFERENCES evaluation_periods (id),
    CONSTRAINT fk_progress_reports_classroom FOREIGN KEY (classroom_id) REFERENCES classrooms (id),
    CONSTRAINT fk_progress_reports_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_progress_reports_teacher FOREIGN KEY (teacher_id) REFERENCES teachers (id),
    CONSTRAINT uk_progress_reports_evaluation UNIQUE (evaluation_id)
);

CREATE INDEX idx_progress_reports_classroom_id ON student_progress_reports (classroom_id);
CREATE INDEX idx_progress_reports_student_id ON student_progress_reports (student_id);
CREATE INDEX idx_progress_reports_period_id ON student_progress_reports (evaluation_period_id);
CREATE INDEX idx_progress_reports_status ON student_progress_reports (status);
