CREATE TABLE tuition_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    sessions_per_week INT NULL,
    total_sessions INT NOT NULL,
    expected_months INT NULL,
    price NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_tuition_packages_name ON tuition_packages (name);
CREATE INDEX idx_tuition_packages_status ON tuition_packages (status);
