package com.englishcenter.dashboard;

public enum DashboardAlertType {
    STUDENT_OUT_OF_SESSIONS,
    STUDENT_LOW_SESSIONS,
    SESSION_ATTENDANCE_NOT_COMPLETED,
    OVERDUE_INVOICES,
    STUDENTS_WITH_MULTIPLE_UNPAID_INVOICES,
    UNASSIGNED_CLASSROOM,
    NEGATIVE_FINANCIAL_ACCOUNT,
    PAYMENT_RECONCILIATION_MISMATCH,
    PREVIOUS_MONTH_NOT_CLOSED,
    TODAY_ASSIGNED_CLASSES,
    TEACHER_SESSION_ATTENDANCE_NOT_COMPLETED,
    TEACHER_STUDENTS_LOW_SESSIONS,
    TEACHER_STUDENTS_OUT_OF_SESSIONS,
    UPCOMING_SESSIONS,
    NEXT_SESSION,
    LOW_REMAINING_SESSIONS,
    OUT_OF_SESSIONS,
    OUTSTANDING_TUITION,
    OVERDUE_INVOICE,
    RECENT_ATTENDANCE
}
