spring:
  profiles:
    default: local
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

app:
  time:
    zone-id: Asia/Ho_Chi_Minh
  security:
    admin:
      username: ${ADMIN_USERNAME:admin}
      password-hash: ${ADMIN_PASSWORD_HASH:$2y$12$RPKRqKLjxVwj9WX67C3C9eqI7FN4dz85ihL3z/qNb.MFKVnmY3uJS}
    jwt:
      secret: ${JWT_SECRET:9CbFNjoKXibbNWlh/VmG3Q2aiYQsn4EoOWADPgLHmaw=}
      expiration-minutes: ${JWT_EXPIRATION_MINUTES:480}
      issuer: ${JWT_ISSUER:school-management-api}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
